In [1]:
import os, sys
sys.path.insert(0, os.path.abspath('../data_prep/'))
import glob
import pandas as pd
import log_prep as lp
import grades_prep as gp
import ml_modeling as mm

In [2]:
# load raw data in log_data, a list where log_data[session number] = dataframe for the session
log_data = lp.read_file(file_dir = '../../data/Processes')
# data preprocessing
manipulated_log_data = lp.feature_manipulation(log_data)
# Standardization
std_manipulated_log_data = lp.feature_standardization(manipulated_log_data)
# Confirm
std_manipulated_log_data[1]

1th element in the sessions list represents Session1
2th element in the sessions list represents Session2
3th element in the sessions list represents Session3
4th element in the sessions list represents Session4
5th element in the sessions list represents Session5
6th element in the sessions list represents Session6

,DUR_Aulaweb,DUR_Blank,DUR_Deeds,DUR_Diagram,DUR_FSM,DUR_Other,DUR_Properties,DUR_Study,DUR_TextEditor,KS_Aulaweb,...,MW_TextEditor,MWC_Aulaweb,MWC_Blank,MWC_Deeds,MWC_Diagram,MWC_FSM,MWC_Other,MWC_Properties,MWC_Study,MWC_TextEditor
ID,,,,,,,,,,,,,,,,,,,,,
1,0.391070,-0.179457,-0.654242,1.829954,-0.136624,-0.428884,-0.115648,-0.224070,-0.697487,-0.328866,...,-0.165969,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
2,-0.421611,-0.184149,1.510162,-0.271872,-0.136624,-0.382100,-0.125472,-0.400680,0.014784,-0.328866,...,-0.540137,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
4,-0.335592,-0.178284,-0.924903,-0.681260,-0.136624,-0.140247,-0.124950,3.130371,-0.538787,-0.108987,...,-0.540137,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
5,-0.144643,0.696927,-0.716053,-0.572595,-0.136624,-0.334972,-0.109272,-0.464936,-0.605063,6.597312,...,-0.027597,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
7,-0.442081,-0.184081,0.960554,1.902585,-0.136624,-0.395839,-0.126639,-0.304684,-0.410831,-0.328866,...,-0.540137,-0.247864,0.0,5.067421,8.717798,0.0,-0.189405,0.0,-0.156168,3.712311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,-0.425529,-0.155233,-0.510397,-0.649011,8.660130,-0.171575,-0.127056,-0.431883,0.566340,-0.328866,...,-0.540137,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
112,-0.411377,-0.142905,-0.527606,1.635353,-0.136624,0.723558,-0.127464,-0.044563,0.021647,-0.328866,...,-0.167381,-0.247864,0.0,0.653491,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
113,-0.416982,-0.156549,0.244563,0.230942,-0.136624,-0.183766,-0.124759,0.054531,-0.187076,-0.328866,...,-0.540137,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
114,0.651882,-0.155482,-0.120882,-0.431595,-0.136624,-0.014028,-0.127250,-0.476102,-0.616094,1.136992,...,-0.540137,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
115,-0.325449,-0.133578,0.205263,-0.613916,-0.136624,-0.006224,-0.128440,-0.393089,-0.017106,-0.328866,...,2.954454,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777

In [3]:
std_manipulated_log_data[0]

0

In [4]:
# Load grading data in grades, a list where 
# grades[0] = intermediate grades
# grades[1] = first-attempt final grades
# grades[2] = second-attempt final grades
grades = gp.read_grades(dir1 = '../../data/intermediate_grades.xlsx',
                        dir2 = '../../data/final_grades.xlsx')
grades[0]

/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:300: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

     Student Id  Session 2  Session 3  Session 4  Session 5  Session 6
0             1        5.0        0.0        4.5        4.0       2.25
1             2        4.0        3.5        4.5        4.0       1.00
2             3        3.5        3.5        4.5        4.0       0.00
3             4        6.0        4.0        5.0        3.5       2.75
4             5        5.0        4.0        5.0        4.0       2.75
..          ...        ...        ...        ...        ...        ...
110         111        3.0        0.0        0.0        3.0       0.00
111         112        0.0        0.0        0.0        0.0       0.00
112         113        0.0        0.0        0.0        0.0       0.00
113         114        0.0        0.0        0.0        0.0       0.00
114         115        0.0        0.0        0.0        0.0       0.00

[115 rows x 6 columns]

In [5]:
# Rebase intermdediate grades into 100
intermediate_grades = gp.rebase_mid(grades[0])
intermediate_grades

      ID    MID2   MID3   MID4   MID5   MID6
0      1   83.33    0.0   90.0  100.0  56.25
1      2   66.67   87.5   90.0  100.0  25.00
2      3   58.33   87.5   90.0  100.0   0.00
3      4  100.00  100.0  100.0   87.5  68.75
4      5   83.33  100.0  100.0  100.0  68.75
..   ...     ...    ...    ...    ...    ...
110  111   50.00    0.0    0.0   75.0   0.00
111  112    0.00    0.0    0.0    0.0   0.00
112  113    0.00    0.0    0.0    0.0   0.00
113  114    0.00    0.0    0.0    0.0   0.00
114  115    0.00    0.0    0.0    0.0   0.00

[115 rows x 6 columns]

In [6]:
# Merge two final grades into final_grades, first-attempt scores prioritized, 100-rebased
final_grades = gp.final_manipulation(grades[1], grades[2])
final_grades

     ID   FIN1  FIN2   FIN3   FIN4        FIN5   FIN6  final_score
0     1  100.0  30.0  100.0  100.0  100.000000  95.00    87.500000
1     2  100.0  50.0   80.0   68.0   43.333333  12.50    58.972222
0     3  100.0  60.0  100.0  100.0   60.000000  82.50    83.750000
2     4  100.0  30.0   50.0   28.0   10.000000  25.00    40.500000
3     5  100.0  70.0  100.0   20.0   80.000000   7.50    62.916667
..  ...    ...   ...    ...    ...         ...    ...          ...
50  101  100.0  30.0   60.0   24.0    0.000000   0.00    35.666667
58  102  100.0  50.0   60.0   60.0    0.000000   7.50    46.250000
59  103  100.0  50.0   80.0   12.0    0.000000   0.00    40.333333
60  104  100.0  50.0  100.0   96.0   86.666667  93.75    87.736111
51  106  100.0  30.0  100.0   28.0    0.000000  55.00    52.166667

[93 rows x 8 columns]

In [7]:
# Combining the intermdediate grades with final one
whole_grades = gp.merge_mid_final(intermediate_grades, final_grades)
whole_grades

,ID,MID2,MID3,MID4,MID5,MID6,FIN1,FIN2,FIN3,FIN4,FIN5,FIN6,final_score
0,1,83.33,0.0,90.0,100.0,56.25,100.0,30.0,100.0,100.0,100.000000,95.00,87.500000
1,2,66.67,87.5,90.0,100.0,25.00,100.0,50.0,80.0,68.0,43.333333,12.50,58.972222
2,3,58.33,87.5,90.0,100.0,0.00,100.0,60.0,100.0,100.0,60.000000,82.50,83.750000
3,4,100.00,100.0,100.0,87.5,68.75,100.0,30.0,50.0,28.0,10.000000,25.00,40.500000
4,5,83.33,100.0,100.0,100.0,68.75,100.0,70.0,100.0,20.0,80.000000,7.50,62.916667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,101,75.00,37.5,0.0,87.5,0.00,100.0,30.0,60.0,24.0,0.000000,0.00,35.666667
89,102,75.00,100.0,80.0,87.5,50.00,100.0,50.0,60.0,60.0,0.000000,7.50,46.250000
90,103,33.33,0.0,0.0,87.5,0.00,100.0,50.0,80.0,12.0,0.000000,0.00,40.333333
91,104,100.00,0.0,90.0,100.0,68.75,100.0,50.0,100.0,96.0,86.666667,93.75,87.736111
92,106,0.00,87.5,0.0,0.0,0.00,100.0,30.0,100.0,28.0,0.000000,55.00,52.166667

In [8]:
# Standardizing the whole score
std_whole_grades = gp.standardize_grades(whole_grades)
std_whole_grades

,MID2,MID3,MID4,MID5,MID6,FIN2,FIN3,FIN4,FIN5,FIN6,ID
0,0.873680,-1.739299,0.139648,0.503558,0.221767,-0.881542,0.730296,1.243222,1.569829,1.448182,1
1,0.359568,0.706238,0.139648,0.503558,-0.936902,-0.053427,-0.134895,0.278217,0.011825,-0.824042,2
2,0.102203,0.706238,0.139648,0.503558,-1.863836,0.360631,0.730296,1.243222,0.470062,1.103906,3
3,1.388100,1.055601,0.639157,0.030519,0.685234,-0.881542,-1.432682,-0.928039,-0.904647,-0.479766,4
4,0.873680,1.055601,0.639157,0.503558,0.685234,0.774689,0.730296,-1.169290,1.019946,-0.961753,5
...,...,...,...,...,...,...,...,...,...,...,...
88,0.616624,-0.691212,-4.355936,0.030519,-1.863836,-0.881542,-1.000087,-1.048665,-1.179589,-1.168319,101
89,0.616624,1.055601,-0.359862,0.030519,-0.009967,-0.053427,-1.000087,0.036966,-1.179589,-0.961753,102
90,-0.669273,-1.739299,-4.355936,0.030519,-1.863836,-0.053427,-0.134895,-1.410541,-1.179589,-1.168319,103
91,1.388100,-1.739299,0.139648,0.503558,0.685234,-0.053427,0.730296,1.122596,1.203240,1.413755,104
92,-1.697806,0.706238,-4.355936,-3.280754,-1.863836,-0.881542,0.730296,-0.928039,-1.179589,0.346498,106

In [9]:
# Completeing all gredes
std_whole_grades_with_stu_behavior = gp.get_result(std_whole_grades)
std_whole_grades_with_stu_behavior

,MID2,MID3,MID4,MID5,MID6,FIN2,FIN3,FIN4,FIN5,FIN6,ID,RES2,RES3,RES4,RES5,RES6
0,0.873680,-1.739299,0.139648,0.503558,0.221767,-0.881542,0.730296,1.243222,1.569829,1.448182,1,1,0,0,0,0
1,0.359568,0.706238,0.139648,0.503558,-0.936902,-0.053427,-0.134895,0.278217,0.011825,-0.824042,2,1,1,1,1,0
2,0.102203,0.706238,0.139648,0.503558,-1.863836,0.360631,0.730296,1.243222,0.470062,1.103906,3,0,1,0,1,0
3,1.388100,1.055601,0.639157,0.030519,0.685234,-0.881542,-1.432682,-0.928039,-0.904647,-0.479766,4,1,1,1,1,1
4,0.873680,1.055601,0.639157,0.503558,0.685234,0.774689,0.730296,-1.169290,1.019946,-0.961753,5,1,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,0.616624,-0.691212,-4.355936,0.030519,-1.863836,-0.881542,-1.000087,-1.048665,-1.179589,-1.168319,101,1,1,0,1,0
89,0.616624,1.055601,-0.359862,0.030519,-0.009967,-0.053427,-1.000087,0.036966,-1.179589,-0.961753,102,1,1,0,1,1
90,-0.669273,-1.739299,-4.355936,0.030519,-1.863836,-0.053427,-0.134895,-1.410541,-1.179589,-1.168319,103,0,0,0,1,0
91,1.388100,-1.739299,0.139648,0.503558,0.685234,-0.053427,0.730296,1.122596,1.203240,1.413755,104,1,0,0,0,0
92,-1.697806,0.706238,-4.355936,-3.280754,-1.863836,-0.881542,0.730296,-0.928039,-1.179589,0.346498,106,0,1,0,0,0

In [10]:
# leave relevant columns only
outcome = std_whole_grades_with_stu_behavior[['ID', 'RES2', 'RES3', 'RES4', 'RES5', 'RES6','MID2','MID3','MID4','MID5','MID6']]
outcome

,ID,RES2,RES3,RES4,RES5,RES6,MID2,MID3,MID4,MID5,MID6
0,1,1,0,0,0,0,0.873680,-1.739299,0.139648,0.503558,0.221767
1,2,1,1,1,1,0,0.359568,0.706238,0.139648,0.503558,-0.936902
2,3,0,1,0,1,0,0.102203,0.706238,0.139648,0.503558,-1.863836
3,4,1,1,1,1,1,1.388100,1.055601,0.639157,0.030519,0.685234
4,5,1,1,1,0,1,0.873680,1.055601,0.639157,0.503558,0.685234
...,...,...,...,...,...,...,...,...,...,...,...
88,101,1,1,0,1,0,0.616624,-0.691212,-4.355936,0.030519,-1.863836
89,102,1,1,0,1,1,0.616624,1.055601,-0.359862,0.030519,-0.009967
90,103,0,0,0,1,0,-0.669273,-1.739299,-4.355936,0.030519,-1.863836
91,104,1,0,0,0,0,1.388100,-1.739299,0.139648,0.503558,0.685234
92,106,0,1,0,0,0,-1.697806,0.706238,-4.355936,-3.280754,-1.863836

In [11]:
std_manipulated_log_data[1]

,DUR_Aulaweb,DUR_Blank,DUR_Deeds,DUR_Diagram,DUR_FSM,DUR_Other,DUR_Properties,DUR_Study,DUR_TextEditor,KS_Aulaweb,...,MW_TextEditor,MWC_Aulaweb,MWC_Blank,MWC_Deeds,MWC_Diagram,MWC_FSM,MWC_Other,MWC_Properties,MWC_Study,MWC_TextEditor
ID,,,,,,,,,,,,,,,,,,,,,
1,0.391070,-0.179457,-0.654242,1.829954,-0.136624,-0.428884,-0.115648,-0.224070,-0.697487,-0.328866,...,-0.165969,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
2,-0.421611,-0.184149,1.510162,-0.271872,-0.136624,-0.382100,-0.125472,-0.400680,0.014784,-0.328866,...,-0.540137,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
4,-0.335592,-0.178284,-0.924903,-0.681260,-0.136624,-0.140247,-0.124950,3.130371,-0.538787,-0.108987,...,-0.540137,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
5,-0.144643,0.696927,-0.716053,-0.572595,-0.136624,-0.334972,-0.109272,-0.464936,-0.605063,6.597312,...,-0.027597,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
7,-0.442081,-0.184081,0.960554,1.902585,-0.136624,-0.395839,-0.126639,-0.304684,-0.410831,-0.328866,...,-0.540137,-0.247864,0.0,5.067421,8.717798,0.0,-0.189405,0.0,-0.156168,3.712311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,-0.425529,-0.155233,-0.510397,-0.649011,8.660130,-0.171575,-0.127056,-0.431883,0.566340,-0.328866,...,-0.540137,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
112,-0.411377,-0.142905,-0.527606,1.635353,-0.136624,0.723558,-0.127464,-0.044563,0.021647,-0.328866,...,-0.167381,-0.247864,0.0,0.653491,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
113,-0.416982,-0.156549,0.244563,0.230942,-0.136624,-0.183766,-0.124759,0.054531,-0.187076,-0.328866,...,-0.540137,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
114,0.651882,-0.155482,-0.120882,-0.431595,-0.136624,-0.014028,-0.127250,-0.476102,-0.616094,1.136992,...,-0.540137,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
115,-0.325449,-0.133578,0.205263,-0.613916,-0.136624,-0.006224,-0.128440,-0.393089,-0.017106,-0.328866,...,2.954454,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777

In [12]:
# merge features and outcome to log_data
def merge_all_data(log_data, grade):
    for i, features in enumerate(log_data):
        if i in [0, 1]: continue
        log_data[i] = features.merge(grade[['ID', 'MID' + str(i), 'RES' + str(i)]], how='inner', on='ID')
        log_data[i] = log_data[i].rename(columns={'RES' + str(i): 'Y'})
    return log_data

In [13]:
whole_data = merge_all_data(std_manipulated_log_data, outcome)
whole_data[1]

,DUR_Aulaweb,DUR_Blank,DUR_Deeds,DUR_Diagram,DUR_FSM,DUR_Other,DUR_Properties,DUR_Study,DUR_TextEditor,KS_Aulaweb,...,MW_TextEditor,MWC_Aulaweb,MWC_Blank,MWC_Deeds,MWC_Diagram,MWC_FSM,MWC_Other,MWC_Properties,MWC_Study,MWC_TextEditor
ID,,,,,,,,,,,,,,,,,,,,,
1,0.391070,-0.179457,-0.654242,1.829954,-0.136624,-0.428884,-0.115648,-0.224070,-0.697487,-0.328866,...,-0.165969,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
2,-0.421611,-0.184149,1.510162,-0.271872,-0.136624,-0.382100,-0.125472,-0.400680,0.014784,-0.328866,...,-0.540137,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
4,-0.335592,-0.178284,-0.924903,-0.681260,-0.136624,-0.140247,-0.124950,3.130371,-0.538787,-0.108987,...,-0.540137,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
5,-0.144643,0.696927,-0.716053,-0.572595,-0.136624,-0.334972,-0.109272,-0.464936,-0.605063,6.597312,...,-0.027597,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
7,-0.442081,-0.184081,0.960554,1.902585,-0.136624,-0.395839,-0.126639,-0.304684,-0.410831,-0.328866,...,-0.540137,-0.247864,0.0,5.067421,8.717798,0.0,-0.189405,0.0,-0.156168,3.712311
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,-0.425529,-0.155233,-0.510397,-0.649011,8.660130,-0.171575,-0.127056,-0.431883,0.566340,-0.328866,...,-0.540137,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
112,-0.411377,-0.142905,-0.527606,1.635353,-0.136624,0.723558,-0.127464,-0.044563,0.021647,-0.328866,...,-0.167381,-0.247864,0.0,0.653491,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
113,-0.416982,-0.156549,0.244563,0.230942,-0.136624,-0.183766,-0.124759,0.054531,-0.187076,-0.328866,...,-0.540137,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
114,0.651882,-0.155482,-0.120882,-0.431595,-0.136624,-0.014028,-0.127250,-0.476102,-0.616094,1.136992,...,-0.540137,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777
115,-0.325449,-0.133578,0.205263,-0.613916,-0.136624,-0.006224,-0.128440,-0.393089,-0.017106,-0.328866,...,2.954454,-0.247864,0.0,-0.229295,-0.114708,0.0,-0.189405,0.0,-0.156168,-0.176777

In [14]:
whole_data[2]

,ID,DUR_Aulaweb,DUR_Blank,DUR_Deeds,DUR_Diagram,DUR_FSM,DUR_Other,DUR_Properties,DUR_Study,DUR_TextEditor,...,MWC_Blank,MWC_Deeds,MWC_Diagram,MWC_FSM,MWC_Other,MWC_Properties,MWC_Study,MWC_TextEditor,MID2,Y
0,1,-0.180077,-0.223501,-0.731890,1.869931,-0.157494,-0.321309,-0.187415,-0.021704,-0.748815,...,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139,0.873680,1
1,2,-0.179064,-0.222049,0.070617,-0.176423,-0.157494,-0.286618,7.977765,-0.568710,0.277439,...,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139,0.359568,1
2,3,-0.179587,-0.002275,-0.522372,-0.207838,-0.157494,0.010717,-0.282903,0.089327,0.620493,...,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139,0.102203,0
3,4,-0.177029,-0.161910,-0.104139,-0.345523,6.866187,-0.009766,-0.252656,-0.647769,-0.400458,...,0.0,1.162062,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139,1.388100,1
4,5,-0.179424,-0.223941,-0.424156,-0.321302,-0.157494,-0.320411,-0.018654,-0.354565,-0.046255,...,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139,0.873680,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,100,-0.143273,0.021325,-0.480431,0.089639,-0.157494,-0.148921,2.125473,-0.342516,-0.724239,...,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139,0.102203,1
71,101,-0.150673,-0.220802,-0.749819,-0.410013,-0.157494,-0.140200,-0.284588,-0.586811,-0.386493,...,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139,0.616624,1
72,102,-0.179400,-0.221470,-0.634870,-0.401461,-0.157494,-0.303834,-0.285515,-0.408132,-0.519668,...,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139,0.616624,1
73,103,-0.176630,-0.224005,-0.398235,0.414184,-0.157494,-0.303077,0.620722,0.361131,1.119425,...,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139,-0.669273,0
74,104,-0.155397,-0.216145,0.127902,-0.050916,-0.157494,-0.302861,-0.179523,0.793276,-0.373707,...,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139,1.388100,1

In [30]:
# laoding packages
from sklearn.model_selection import train_test_split
from sklearn.ensemble import ExtraTreesClassifier
import pandas as pd



def subset_important_features(data_list, num_of_features):
    """
    parameters:
    datasets: dataframe with 
    num_of_features
    option:
    """
    important_features = [0, 1]
    for i, session in enumerate(data_list):
        if i in [0,1]: continue
        X = session.drop(columns=['ID', 'Y'])
        y = session['Y']
        clf = ExtraTreesClassifier(n_estimators=50)
        clf = clf.fit(X, y)
        feat_importances = pd.Series(clf.feature_importances_, index=X.columns)
        features = feat_importances.nlargest(num_of_features).index[0:num_of_features]
        important_features.append(pd.DataFrame(features, columns = ['session'+str(i)]))
        important_features[i].loc[num_of_features] = ['Y']
        important_features[i].loc[num_of_features+1] = ['ID']
            
    for i, session in enumerate(data_list):
        if i in [0,1]: continue
        data_list[i] = session[important_features[i]['session'+str(i)]] 

    return data_list

In [36]:
dt1 = whole_data.copy()

data_important_features = subset_important_features(dt1, 3)
# data_common_important_features = mm.subset_important_features(dt1, 2, "common")
data_important_features[4]

        MID4  MCR_Diagram  MW_Study  Y  ID
0   0.139648    -0.407992  0.100813  0   1
1   0.139648    -0.553677 -0.076146  1   2
2   0.139648     6.512051 -0.249173  0   3
3   0.639157    -0.407992 -0.146930  1   4
4   0.639157     0.065485 -0.504782  1   5
..       ...          ...       ... ..  ..
82  0.639157    -0.626520  1.622666  1  94
83  0.639157    -0.407992 -0.241309  1  95
84  0.639157     1.485915 -0.064349  1  96
85  0.639157    -0.699362 -0.492984  1  98
86 -0.359862    -0.371571 -0.099741  1  99

[87 rows x 5 columns]

In [57]:
# save session data in pickle
for i in [2, 3, 4, 5, 6]:
    filename = 'data_session_' + str(i)
    pickle.dump(data_important_features[i], open(filename, 'wb'))

In [55]:
df = data_important_features[4]
df.loc[df['ID'] == 1].drop(columns=['Y', 'ID'])

       MID4  MCR_Diagram  MW_Study
0  0.139648    -0.407992  0.100813

In [50]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import pickle

def machine_learning_model(data_list, ml_model):
    for i, session in enumerate(data_list):
        result_list = [0,1]
        if i in [0, 1]: continue
        X = session.drop(columns=['Y', 'ID'])
        y = session['Y']
        if ml_model == 'KNN':
            cKNN = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski', p = 2).fit(X, y)
            predict = cKNN.predict(X)
            session = session.assign(Predicted_Y = predict)
        elif ml_model == 'DT':
            cDT = DecisionTreeClassifier(criterion = 'entropy', random_state = 0).fit(X, y)
            predict = cDT.predict(X)
            session = session.assign(Predicted_Y = predict)
        elif ml_model == 'RF':
            cRF = RandomForestClassifier(n_estimators = 10, criterion ='entropy', random_state = 0).fit(X, y)
            predict = cRF.predict(X)
            session = session.assign(Predicted_Y = predict)
        elif ml_model == 'NB':
            cNB = GaussianNB().fit(X, y)
            predict = cNB.predict(X)
            session = session.assign(Predicted_Y = predict)
        elif ml_model == 'LR':
            cLR = LogisticRegression(solver = 'liblinear', random_state = 0).fit(X, y)
            predict = cLR.predict(X)
            filename = 'log_regression_' + str(i)
            pickle.dump(cLR, open(filename, 'wb'))
            print(accuracy_score(y, predict))
            session = session.assign(Predicted_Y = predict)
        elif model == 'SVC':
            cSVM = SVC(kernel = 'rbf', random_state=0).fit(X, y)
            predict = cSVM.predict(X)
            session = session.assign(Predicted_Y = predict)
        result_list.append(session)
    return result_list

In [51]:
# run LR model and build the pickle for model
student_behavior_predictions = machine_learning_model(data_important_features, 'LR')
student_behavior_predictions[2]

0.7333333333333333
0.8701298701298701
0.8045977011494253
0.6785714285714286
0.7215189873417721

        MID6  KS_TextEditor  KS_Other  Y   ID  Predicted_Y
0   0.221767       0.358436 -0.103669  0    1            1
1  -0.936902       0.239186  0.785985  0    2            0
2   0.685234       0.618799 -0.370275  1    4            1
3   0.685234       0.298811 -0.378969  1    5            1
4   0.916968       2.705675  1.800248  1    6            1
..       ...            ...       ... ..  ...          ...
74  0.221767      -1.096414 -0.390560  0   96            1
75  0.916968      -0.200051 -0.274645  1   98            1
76 -0.473434      -0.567739 -0.321011  1   99            0
77 -0.009967      -1.136164 -0.390560  1  102            1
78  0.685234       0.513461 -0.292032  0  104            1

[79 rows x 6 columns]

In [80]:
def review_alert(id):
    res = [0]*7
    for num in [2, 3, 4, 5, 6]:
        data = 'data_session_' + str(num)
        df = pickle.load(open(data, 'rb'))
        features = df.loc[df['ID'] == int(id)].drop(columns=['Y', 'ID'])
        if len(features) == 0:
            continue
        
        model = 'log_regression_' + str(num)
        loaded_model = pickle.load(open(model, 'rb'))
        res[num] = loaded_model.predict(features)[0]
    return res

In [81]:
review_alert(3)

[0, 0, 1, 1, 0, 1, 0]