## 1. Package Loading

In [1]:
import os
import sys
sys.path.insert(0, os.path.abspath('../data_prep/'))
import glob
import pickle
import pandas as pd
import log_prep1 as lp
import grades_prep1 as gp
import ml_modeling as mm
from sklearn.metrics import accuracy_score

## 2. Log data management process

### Load log data files

In [2]:
log_data = lp.read_file()
log_data

1th element in the sessions list represents Session1
2th element in the sessions list represents Session2
3th element in the sessions list represents Session3
4th element in the sessions list represents Session4
5th element in the sessions list represents Session5
6th element in the sessions list represents Session6

[0,
      session  student_id exercise            activity           start_time  \
 0          1           1       Es               Other   2.10.2014 11:25:33
 1          1           1       Es             Aulaweb   2.10.2014 11:25:35
 2          1           1       Es               Blank   2.10.2014 11:25:43
 3          1           1       Es               Deeds   2.10.2014 11:25:44
 4          1           1       Es               Other   2.10.2014 11:26:18
 ..       ...         ...      ...                 ...                  ...
 351        1          98   Es_1_4             Diagram   2.10.2014 13:10:41
 352        1          98   Es_1_4        Deeds_Es_1_4   2.10.2014 13:10:44
 353        1          98   Es_1_4   TextEditor_Es_1_4   2.10.2014 13:10:48
 354        1          98   Es_1_4        Deeds_Es_1_4   2.10.2014 13:11:13
 355        1          98   Es_1_4        Study_Es_1_4   2.10.2014 13:11:14

                 end_time  idle_time  mouse_wheel  mouse_wheel_click  \
 0     2.10.2014 11:25:34          0            0                  0
 1     2.10.2014 11:25:42        218            0                  0
 2     2.10.2014 11:25:43          0            0                  0
 3     2.10.2014 11:26:17     154117            6                  0
 4     2.10.2014 11:26:18          0            0                  0
 ..                   ...        ...          ...                ...
 351   2.10.2014 13:10:43          0            0                  0
 352   2.10.2014 13:10:47          0            0                  0
 353   2.10.2014 13:11:12      32501          342                  0
 354   2.10.2014 13:11:13          0            0                  0
 355   2.10.2014 13:11:15         16            0                  0

      mouse_click_left  mouse_click_right  mouse_movement  keystroke
 0                   0                  0              84          0
 1                   4                  0             397          0
 2                   0                  0              59          0
 3                   8                  0            1581          4
 4                   2                  0             103          0
 ..                ...                ...             ...        ...
 351                 2                  0             135          0
 352                 2                  0             104          0
 353                 6                  0             181         95
 354                 2                  0               8          0
 355                 2                  0              62          0

 [34294 rows x 13 columns],
      session  student_id exercise            activity            start_time  \
 0          2           1       Es        Study_Es_2_1    16.10.2014 11:25:9
 1          2           1   Es_2_1        Study_Es_2_1   16.10.2014 11:25:10
 2          2           1   Es_2_1        Deeds_Es_2_1   16.10.2014 11:25:12
 3          2           1   Es_2_1        Study_Es_2_1   16.10.2014 11:25:16
 4          2           1   Es_2_1   TextEditor_Es_2_1   16.10.2014 11:25:49
 ..       ...         ...      ...                 ...                   ...
 341        2          99   Es_2_5        Study_Es_2_5    16.10.2014 13:54:8
 342        2          99   Es_2_5        Deeds_Es_2_5   16.10.2014 13:54:10
 343        2          99   Es_2_5             Aulaweb   16.10.2014 13:54:11
 344        2          99   Es_2_5               Other   16.10.2014 13:54:13
 345        2          99   Es_2_5               Blank   16.10.2014 13:54:17

                  end_time  idle_time  mouse_wheel  mouse_wheel_click  \
 0     16.10.2014 11:25:10          0            0                  0
 1     16.10.2014 11:25:11         62            0                  0
 2     16.10.2014 11:25:15        344            0                  0
 3     16.10.2014 11:25:47     143691            7                  0
 4     16.10.2014 11:25:54        127            0                  0
 ..                    ...        ...          ...                ...
 341    16.10.2014 13:54:9         16            0                  0
 342   16.10.2014 13:54:10          0            0                  0
 343   16.10.2014 13:54:12        203            0                  0
 344   16.10.2014 13:54:16         93            0                  0
 345   16.10.2014 13:54:18         31            0                  0

      mouse_click_left  mouse_click_right  mouse_movement  keystroke
 0                   0                  0               0          0
 1                   2                  0             176          0
 2                   4                  0             276          0
 3                   2                  0             898          0
 4                   5                  0             472          0
 ..                ...                ...             ...        ...
 341                 3                  0              41          0
 342                 1                  0              15          0
 343                 4                  0              41          0
 344                 2                  0              85          0
 345                 4                  0              33          0

 [39549 rows x 13 columns],
      session  student_id exercise            activity            start_time  \
 0          3          10       Es               Other   23.10.2014 11:13:57
 1          3          10       Es               Blank    23.10.2014 11:14:1
 2          3          10       Es               Other    23.10.2014 11:14:3
 3          3          10       Es               Other    23.10.2014 11:14:5
 4          3          10   Es_3_1        Study_Es_3_1    23.10.2014 11:14:7
 ..       ...         ...      ...                 ...                   ...
 365        3          99   Es_3_4             Diagram   23.10.2014 13:54:59
 366        3          99   Es_3_4        Study_Es_3_4   23.10.2014 13:55:12
 367        3          99   Es_3_4   TextEditor_Es_3_4   23.10.2014 13:55:13
 368        3          99   Es_3_4               Other   23.10.2014 13:55:16
 369        3          99   Es_3_4               Blank   23.10.2014 13:55:18

                  end_time  idle_time  mouse_wheel  mouse_wheel_click  \
 0      23.10.2014 11:14:0       2483            0                  0
 1      23.10.2014 11:14:2          0            0                  0
 2      23.10.2014 11:14:4         15            0                  0
 3      23.10.2014 11:14:5          0            0                  0
 4     23.10.2014 11:14:15        544            0                  0
 ..                    ...        ...          ...                ...
 365   23.10.2014 13:55:11       4295            0                  0
 366   23.10.2014 13:55:12          0            0                  0
 367   23.10.2014 13:55:15         63            0                  0
 368   23.10.2014 13:55:17        453            0                  0
 369   23.10.2014 13:55:19         16            0                  0

      mouse_click_left  mouse_click_right  mouse_movement  keystroke
 0                   0                  0              99          0
 1                   2                  0             133          0
 2                   2                  0             169          0
 3                   2                  0              74          0
 4                  16                  0             669          0
 ..                ...                ...             ...        ...
 365                12                  2             686          0
 366                 4                  0              73          0
 367                 3                  0             137          0
 368                 2                  0             119          0
 369                 5                  0             130          0

 [29127 rows x 13 columns],
      session  student_id exercise            activity            start_time  \
 0          4           1       Es               Other    13.11.2014 11:8:14
 1          4           1       Es               Other    13.11.2014 11:8:16
 2          4           1   Es_4_1        Study_Es_4_1    13.11.2014 11:8:17
 3          4           1   Es_4_1               Blank    13.11.2014 11:8:21
 4          4           1   Es_4_2        Study_Es_4_2    13.11.2014 11:8:23
 ..       ...         ...      ...                 ...                   ...
 441        4          99   Es_4_4   TextEditor_Es_4_4   13.11.2014 12:23:50
 442        4          99   Es_4_2   TextEditor_Es_4_2   13.11.2014 12:23:53
 443        4          99   Es_4_1   TextEditor_Es_4_1   13.11.2014 12:23:56
 444        4          99   Es_4_1               Other    13.11.2014 12:24:0
 445        4          99   Es_4_1               Other    13.11.2014 12:24:2

                  end_time  idle_time  mouse_wheel  mouse_wheel_click  \
 0      13.11.2014 11:8:15         94            0                  0
 1      13.11.2014 11:8:16          0            0                  0
 2      13.11.2014 11:8:20        189            0                  0
 3      13.11.2014 11:8:22         16            0                  0
 4      13.11.2014 11:8:25          0            0                  0
 ..                    ...        ...          ...                ...
 441   13.11.2014 12:23:52         32           33                  0
 442   13.11.2014 12:23:54          0           29                  0
 443   13.11.2014 12:23:59         45           55                  0
 444    13.11.2014 12:24:1          0            0                  0
 445    13.11.2014 12:24:2          0            0                  0

      mouse_click_left  mouse_click_right  mouse_movement  keystroke
 0                   0                  0              50          0
 1                   2                  0              15          0
 2                   2                  0             269          0
 3                   2                  0             183          0
 4                   2                  0             198          0
 ..                ...                ...             ...        ...
 441                 2                  0             163          0
 442                 2                  0             150          0
 443                 2                  0             393          0
 444                 4                  0             177          0
 445                 2                  0             102          0

 [39709 rows x 13 columns],
      session  student_id exercise       activity            start_time  \
 0          5           1       Es          Other    20.11.2014 11:5:34
 1          5           1       Es          Other    20.11.2014 11:5:37
 2          5           1       Es          Other    20.11.2014 11:5:50
 3          5           1       Es     TextEditor    20.11.2014 11:5:54
 4          5           1       Es          Other    20.11.2014 11:5:55
 ..       ...         ...      ...            ...                   ...
 389        5          99   Es_5_4        Diagram   20.11.2014 12:50:22
 390        5          99   Es_5_4     Properties   20.11.2014 12:50:23
 391        5          99   Es_5_4   Deeds_Es_5_4   20.11.2014 12:50:24
 392        5          99   Es_5_4     Properties   20.11.2014 12:50:25
 393        5          99   Es_5_4   Study_Es_5_4   20.11.2014 12:50:26

                  end_time  idle_time  mouse_wheel  mouse_wheel_click  \
 0      20.11.2014 11:5:36       32.0            0                  0
 1      20.11.2014 11:5:49     3706.0            0                  0
 2      20.11.2014 11:5:53      171.0            0                  0
 3      20.11.2014 11:5:54        0.0            0                  0
 4      20.11.2014 11:5:56        0.0            0                  0
 ..                    ...        ...          ...                ...
 389   20.11.2014 12:50:22        0.0            0                  0
 390   20.11.2014 12:50:23        0.0            0                  0
 391   20.11.2014 12:50:24        0.0            0                  0
 392   20.11.2014 12:50:25        0.0            0                  0
 393   20.11.2014 12:50:26        0.0            0                  0

      mouse_click_left  mouse_click_right  mouse_movement  keystroke
 0                   0                  0             166          0
 1                  10                  2             742         16
 2                   6                  0             283          6
 3                   2                  0              85          0
 4                   4                  0             122          0
 ..                ...                ...             ...        ...
 389                 1                  0              73          0
 390                 6                  0              64          0
 391                 2                  0              76          0
 392                 2                  0              62          0
 393                 2                  0              93          0

 [34467 rows x 13 columns],
      session  student_id exercise     activity            start_time  \
 0          6           1       Es        Other   11.12.2014 11:14:22
 1          6           1       Es        Other   11.12.2014 11:14:23
 2          6           1   Es_6_1   FSM_Es_6_1   11.12.2014 11:14:24
 3          6           1   Es_6_1        Other   11.12.2014 11:14:48
 4          6           1   Es_6_1   FSM_Es_6_1   11.12.2014 11:14:50
 ..       ...         ...      ...          ...                   ...
 524        6          99   Es_6_3      Aulaweb   11.12.2014 13:47:30
 525        6          99   Es_6_3        Other   11.12.2014 13:47:36
 526        6          99   Es_6_3        Other   11.12.2014 13:47:37
 527        6          99   Es_6_3   FSM_Es_6_3   11.12.2014 13:47:40
 528        6          99   Es_6_3   Properties   11.12.2014 13:47:41

                  end_time  idle_time  mouse_wheel  mouse_wheel_click  \
 0     11.12.2014 11:14:23          0            0                  0
 1     11.12.2014 11:14:23          0            0                  0
 2     11.12.2014 11:14:47      10778            0                  0
 3     11.12.2014 11:14:49        218            0                  0
 4     11.12.2014 11:15:10       7354            1                  0
 ..                    ...        ...          ...                ...
 524   11.12.2014 13:47:35         60           30                  0
 525   11.12.2014 13:47:36          0            0                  0
 526   11.12.2014 13:47:39         64            0                  0
 527   11.12.2014 13:47:40          0            0                  0
 528   11.12.2014 13:47:41          0            0                  0

      mouse_click_left  mouse_click_right  mouse_movement  keystroke
 0                   0                  0               0          0
 1                   2                  0              86          0
 2                  14                  0            1487          0
 3                   2                  0              84          0
 4                  22                  0            1207          2
 ..                ...                ...             ...        ...
 524                 1                  0             250          0
 525                 3                  0              37          0
 526                 2                  2             283          0
 527                 2                  0              67          0
 528                 2                  0             103          0

 [53170 rows x 13 columns]]

### Manipulate log data

In [3]:
manipulated_log_data = lp.feature_manipulation(log_data)
manipulated_log_data[2] # Session 2

,DUR_Aulaweb,DUR_Blank,DUR_Deeds,DUR_Diagram,DUR_FSM,DUR_Other,DUR_Properties,DUR_Study,DUR_TextEditor,KS_Aulaweb,...,MW_TextEditor,MWC_Aulaweb,MWC_Blank,MWC_Deeds,MWC_Diagram,MWC_FSM,MWC_Other,MWC_Properties,MWC_Study,MWC_TextEditor
ID,,,,,,,,,,,,,,,,,,,,,
1,1108.0,15296.0,33635659.0,8685148.0,0.0,39820.0,3493.0,100878318.0,118425808.0,0.0,...,1191.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,13063.0,27628.0,152742872.0,898633.0,0.0,419913.0,294227.0,14462337.0,347521629.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,6891.0,1894304.0,64732143.0,779097.0,0.0,3677630.0,93.0,118419039.0,424103241.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,37073.0,538424.0,126805821.0,255194.0,93.0,3453213.0,1170.0,1972457.0,196191366.0,29.0,...,2022.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
5,8813.0,11555.0,79309264.0,347358.0,0.0,49656.0,9502.0,48292987.0,275261872.0,0.0,...,1280.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,348051.0,38214.0,30974648.0,9805.0,0.0,2024124.0,33.0,11602697.0,199308768.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
102,9099.0,32547.0,48035277.0,42348.0,0.0,231288.0,0.0,39830462.0,169579497.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
103,41778.0,11014.0,83156320.0,3145933.0,0.0,239583.0,32268.0,161358754.0,535482141.0,0.0,...,1286.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
104,292310.0,77768.0,161245059.0,1376193.0,0.0,241945.0,3774.0,229629087.0,202163111.0,0.0,...,724.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
107,8162837.0,27688606.0,214036257.0,5549197.0,0.0,5683776.0,9535.0,522537155.0,126792800.0,0.0,...,3758.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,2.0,2.0

### Standardize log data

In [4]:
std_manipulated_log_data = lp.feature_standardization(manipulated_log_data)
std_manipulated_log_data[1] # Session 2

,DUR_Aulaweb,DUR_Blank,DUR_Deeds,DUR_Diagram,DUR_FSM,DUR_Other,DUR_Properties,DUR_Study,DUR_TextEditor,KS_Aulaweb,...,MW_TextEditor,MWC_Aulaweb,MWC_Blank,MWC_Deeds,MWC_Diagram,MWC_FSM,MWC_Other,MWC_Properties,MWC_Study,MWC_TextEditor
ID,,,,,,,,,,,,,,,,,,,,,
1,-0.180077,-0.223501,-0.731890,1.869931,-0.157494,-0.321309,-0.187415,-0.021704,-0.748815,-0.225401,...,0.078659,-0.227076,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139
2,-0.179064,-0.222049,0.070617,-0.176423,-0.157494,-0.286618,7.977765,-0.568710,0.277439,-0.225401,...,-0.681333,-0.227076,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139
3,-0.179587,-0.002275,-0.522372,-0.207838,-0.157494,0.010717,-0.282903,0.089327,0.620493,-0.225401,...,-0.681333,-0.227076,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139
4,-0.177029,-0.161910,-0.104139,-0.345523,6.866187,-0.009766,-0.252656,-0.647769,-0.400458,0.439615,...,0.608930,-0.227076,0.0,1.162062,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139
5,-0.179424,-0.223941,-0.424156,-0.321302,-0.157494,-0.320411,-0.018654,-0.354565,-0.046255,-0.225401,...,0.135451,-0.227076,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,-0.150673,-0.220802,-0.749819,-0.410013,-0.157494,-0.140200,-0.284588,-0.586811,-0.386493,-0.225401,...,-0.681333,-0.227076,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139
102,-0.179400,-0.221470,-0.634870,-0.401461,-0.157494,-0.303834,-0.285515,-0.408132,-0.519668,-0.225401,...,-0.681333,-0.227076,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139
103,-0.176630,-0.224005,-0.398235,0.414184,-0.157494,-0.303077,0.620722,0.361131,1.119425,-0.225401,...,0.139280,-0.227076,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139
104,-0.155397,-0.216145,0.127902,-0.050916,-0.157494,-0.302861,-0.179523,0.793276,-0.373707,-0.225401,...,-0.219339,-0.227076,0.0,-0.180038,0.0,0.0,-0.111111,0.0,-0.283103,-0.250139
107,0.511641,3.034631,0.483592,1.045780,-0.157494,0.193819,-0.017727,2.647356,-0.711335,-0.225401,...,1.716693,-0.227076,0.0,7.872562,0.0,0.0,-0.111111,0.0,0.344315,1.327660

### Check the data structure

In [5]:
# The original data include six sessions.
# std_manipulated_log_data[0] is session 1's log data
# std_manipulated_log_data[5] is session 6's log data
len(std_manipulated_log_data)

6

### Save the manipualted log data

In [6]:
# If a user wants to use save them, 
# the user can save them as csv files by using the save_data function
# lp.save_data(manipulated_log_data)

## 3. Intermediate and final grade data management process

### Load grades

In [7]:
grades = gp.read_grades()
grades[1] # Session 2's intermeduate scores

C:\Users\Youngwon\Anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

,Student ID,ES 1.1 \n(2 points),ES 1.2 \n(3 points),ES 2.1\n(2 points),ES 2.2\n(3 points),ES 3.1\n(1 points),ES 3.2\n(2 points),ES 3.3\n(2 points),ES 3.4\n(2 points),ES 3.5\n(3 points),ES 4.1\n(15 points),ES 4.2\n(10 points),ES 5.1\n(2 points),ES 5.2\n(10 points),ES 5.3\n(3 points),ES 6.1\n(25 points),ES 6.2\n(15 points),TOTAL\n(100 points)
0,3,2.0,3,1.0,2.0,1,2,2,2.0,3.0,15.0,10.0,1,5.0,3.0,18.0,15,85.0
1,6,2.0,3,2.0,3.0,1,2,2,0.0,3.0,15.0,7.0,2,9.0,3.0,13.0,15,82.0
2,7,2.0,3,1.0,1.5,1,2,0,0.0,3.0,5.0,4.0,0,0.0,3.0,17.0,10,52.5
3,10,2.0,3,2.0,1.5,1,2,0,2.0,3.0,11.0,1.0,2,10.0,1.5,7.0,10,59.0
4,13,2.0,3,2.0,1.5,1,2,2,2.0,3.0,14.5,10.0,2,2.0,3.0,25.0,15,90.0
5,15,2.0,3,1.0,2.0,1,2,2,2.0,3.0,15.0,10.0,2,4.0,1.5,2.0,15,67.5
6,16,2.0,3,1.0,0.0,1,2,2,2.0,3.0,3.0,9.0,1,0.0,3.0,20.0,15,67.0
7,17,2.0,3,1.0,2.0,1,2,2,2.0,3.0,15.0,10.0,2,10.0,3.0,24.0,15,97.0
8,18,1.0,3,2.0,3.0,1,2,2,2.0,3.0,15.0,7.0,2,2.5,1.5,5.0,10,62.0
9,20,2.0,3,2.0,0.0,1,2,2,2.0,1.5,15.0,10.0,0,0.0,3.0,5.0,10,58.5
10,24,2.0,3,1.0,1.5,1,2,2,2.0,3.0,11.0,1.0,0,0.0,3.0,0.0,0,32.5
11,27,2.0,3,1.0,2.0,1,2,0,2.0,3.0,15.0,9.0,0,0.0,0.0,24.5,10,74.5
12,28,2.0,3,1.0,2.0,1,2,2,2.0,0.0,15.0,8.5,2,4.0,3.0,19.0,13,79.5
13,29,2.0,3,2.0,0.0,1,2,2,2.0,3.0,15.0,10.0,2,10.0,3.0,25.0,15,97.0
14,30,0.0,0,2.0,0.0,0,0,0,0.0,0.0,3.0,2.0,0,0.0,0.0,0.0,0,7.0
15,32,2.0,3,2.0,1.5,1,2,2,2.0,3.0,15.0,10.0,2,10.0,3.0,12.0,5,75.5
16,36,2.0,3,1.0,0.0,1,1,0,2.0,3.0,13.0,9.0,2,10.0,3.0,16.0,13,79.0
17,37,2.0,3,1.0,0.0,0,2,0,2.0,0.0,8.0,1.0,0,0.0,0.0,0.0,0,19.0
18,39,2.0,3,2.0,0.0,0,0,0,2.0,0.0,3.0,4.0,0,0.0,0.0,10.0,15,41.0
19,41,2.0,3,2.0,3.0,1,2,2,2.0,3.0,13.0,10.0,2,10.0,3.0,25.0,15,98.0
20,44,2.0,3,1.0,2.0,1,2,2,2.0,3.0,3.0,7.0,0,5.0,3.0,4.0,10,50.0
21,46,2.0,3,1.0,0.0,1,2,0,0.0,0.0,2.0,1.0,0,0.0,0.0,0.0,0,12.0
22,48,2.0,3,2.0,3.0,1,2,2,2.0,3.0,15.0,7.0,0,2.5,2.0,10.0,15,71.5
23,51,1.5,0,0.0,0.0,1,2,2,2.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,8.5
24,53,1.0,3,1.0,1.0,1,2,2,2.0,3.0,15.0,7.0,1,8.0,1.5,12.0,10,70.5
25,56,2.0,3,2.0,2.0,1,2,2,0.0,0.0,15.0,10.0,1,4.0,1.5,18.0,8,71.5
26,59,2.0,3,2.0,0.0,1,2,2,2.0,3.0,3.0,7.0,2,8.0,3.0,0.0,0,40.0
27,62,2.0,3,1.0,0.0,1,2,2,2.0,3.0,3.0,3.0,0,0.0,0.0,0.0,0,22.0
28,63,2.0,3,2.0,2.0,1,2,2,2.0,3.0,7.0,6.0,2,10.0,3.0,12.0,10,69.0
29,66,2.0,3,2.0,3.0,1,2,2,2.0,3.0,15.0,10.0,2,8.0,3.0,18.0,10,86.0
30,67,2.0,3,1.0,2.0,1,2,2,2.0,3.0,14.5,10.0,2,8.0,3.0,15.0,10,80.5
31,68,2.0,3,2.0,3.0,1,2,2,1.5,3.0,13.0,7.0,2,10.0,3.0,5.0,3,62.5
32,72,2.0,3,2.0,2.0,1,2,2,2.0,3.0,15.0,7.0,2,10.0,3.0,24.0,15,95.0
33,73,2.0,3,1.0,0.0,1,2,0,0.0,3.0,3.0,4.0,0,0.0,1.5,3.0,5,28.5
34,74,1.5,2,1.5,0.0,1,2,0,2.0,3.0,3.0,2.0,0,0.0,0.0,0.0,0,18.0
35,76,2.0,3,2.0,1.5,1,2,2,2.0,2.0,15.0,10.0,2,10.0,3.0,24.0,12,93.5
36,78,2.0,3,1.0,2.0,1,2,2,2.0,3.0,15.0,4.0,0,5.0,1.5,24.5,10,78.0
37,81,2.0,3,1.0,0.0,1,2,2,2.0,3.0,15.0,7.0,2,4.0,3.0,25.0,15,87.0
38,83,2.0,3,2.0,0.0,1,2,0,2.0,0.0,3.0,3.0,2,4.0,1.5,10.0,0,35.5
39,85,2.0,3,2.0,1.5,1,2,2,2.0,3.0,13.0,10.0,2,0.0,1.5,25.0,12,82.0
40,86,2.0,3,2.0,3.0,1,2,2,2.0,3.0,15.0,10.0,1,5.0,3.0,25.0,15,94.0
41,87,2.0,3,1.5,1.5,1,2,2,2.0,3.0,3.0,4.0,0,0.0,0.0,8.0,13,46.0
42,88,2.0,3,1.0,2.0,1,2,2,2.0,3.0,15.0,10.0,2,8.0,3.0,25.0,15,96.0
43,89,2.0,3,1.5,0.0,1,2,0,2.0,3.0,0.0,2.0,0,0.0,0.0,0.0,0,16.5
44,92,1.5,3,1.0,0.0,1,2,0,2.0,0.0,3.0,6.0,0,0.0,0.0,0.0,0,19.5
45,93,2.0,3,2.0,1.5,1,2,2,2.0,3.0,3.0,6.0,0,0.0,1.5,24.0,13,66.0
46,96,2.0,3,2.0,1.5,1,2,2,2.0,3.0,15.0,7.0,2,10.0,3.0,12.0,10,77.5
47,98,2.0,3,1.0,2.0,1,2,2,2.0,3.0,13.0,10.0,2,4.0,1.5,10.0,8,66.5
48,99,1.5,3,0.0,0.0,1,2,0,2.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0,9.5
49,100,2.0,3,1.0,1.5,1,2,2,2.0,3.0,13.0,7.0,2,8.0,1.5,24.0,10,83.0
50,101,2.0,3,0.5,1.0,1,2,0,0.0,3.0,3.0,3.0,0,0.0,0.0,0.0,0,18.5
51,106,2.0,3,1.5,0.0,1,2,2,2.0,3.0,3.0,4.0,0,0.0,0.0,7.0,15,45.5

### Choose one of the highest scores between two final grades

In [8]:
final_grades = gp.final_manipulation(grades[1], grades[2])
final_grades

     ID   FIN1  FIN2   FIN3   FIN4        FIN5   FIN6  final_score
0     1  100.0  30.0  100.0  100.0  100.000000  95.00    87.500000
1     2  100.0  50.0   80.0   68.0   43.333333  12.50    58.972222
0     3  100.0  60.0  100.0  100.0   60.000000  82.50    83.750000
2     4  100.0  30.0   50.0   28.0   10.000000  25.00    40.500000
3     5  100.0  70.0  100.0   20.0   80.000000   7.50    62.916667
..  ...    ...   ...    ...    ...         ...    ...          ...
50  101  100.0  30.0   60.0   24.0    0.000000   0.00    35.666667
58  102  100.0  50.0   60.0   60.0    0.000000   7.50    46.250000
59  103  100.0  50.0   80.0   12.0    0.000000   0.00    40.333333
60  104  100.0  50.0  100.0   96.0   86.666667  93.75    87.736111
51  106  100.0  30.0  100.0   28.0    0.000000  55.00    52.166667

[93 rows x 8 columns]

### Transform the intermdediate grades (random scores) into 100 score bases

In [9]:
intermediate_grades = gp.rebase_mid(grades[0])
intermediate_grades

      ID    MID2   MID3   MID4   MID5   MID6
0      1   83.33    0.0   90.0  100.0  56.25
1      2   66.67   87.5   90.0  100.0  25.00
2      3   58.33   87.5   90.0  100.0   0.00
3      4  100.00  100.0  100.0   87.5  68.75
4      5   83.33  100.0  100.0  100.0  68.75
..   ...     ...    ...    ...    ...    ...
110  111   50.00    0.0    0.0   75.0   0.00
111  112    0.00    0.0    0.0    0.0   0.00
112  113    0.00    0.0    0.0    0.0   0.00
113  114    0.00    0.0    0.0    0.0   0.00
114  115    0.00    0.0    0.0    0.0   0.00

[115 rows x 6 columns]

### Combine the intermdediate grades with final grades

In [10]:
whole_grades = gp.merge_mid_final(intermediate_grades, final_grades)
whole_grades

,ID,MID2,MID3,MID4,MID5,MID6,FIN1,FIN2,FIN3,FIN4,FIN5,FIN6,final_score
0,1,83.33,0.0,90.0,100.0,56.25,100.0,30.0,100.0,100.0,100.000000,95.00,87.500000
1,2,66.67,87.5,90.0,100.0,25.00,100.0,50.0,80.0,68.0,43.333333,12.50,58.972222
2,3,58.33,87.5,90.0,100.0,0.00,100.0,60.0,100.0,100.0,60.000000,82.50,83.750000
3,4,100.00,100.0,100.0,87.5,68.75,100.0,30.0,50.0,28.0,10.000000,25.00,40.500000
4,5,83.33,100.0,100.0,100.0,68.75,100.0,70.0,100.0,20.0,80.000000,7.50,62.916667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,101,75.00,37.5,0.0,87.5,0.00,100.0,30.0,60.0,24.0,0.000000,0.00,35.666667
89,102,75.00,100.0,80.0,87.5,50.00,100.0,50.0,60.0,60.0,0.000000,7.50,46.250000
90,103,33.33,0.0,0.0,87.5,0.00,100.0,50.0,80.0,12.0,0.000000,0.00,40.333333
91,104,100.00,0.0,90.0,100.0,68.75,100.0,50.0,100.0,96.0,86.666667,93.75,87.736111
92,106,0.00,87.5,0.0,0.0,0.00,100.0,30.0,100.0,28.0,0.000000,55.00,52.166667

### Standardize the whole scores

In [11]:
std_whole_grades = gp.standardize_grades(whole_grades)
std_whole_grades

,MID2,MID3,MID4,MID5,MID6,FIN2,FIN3,FIN4,FIN5,FIN6,ID
0,0.873680,-1.739299,0.139648,0.503558,0.221767,-0.881542,0.730296,1.243222,1.569829,1.448182,1
1,0.359568,0.706238,0.139648,0.503558,-0.936902,-0.053427,-0.134895,0.278217,0.011825,-0.824042,2
2,0.102203,0.706238,0.139648,0.503558,-1.863836,0.360631,0.730296,1.243222,0.470062,1.103906,3
3,1.388100,1.055601,0.639157,0.030519,0.685234,-0.881542,-1.432682,-0.928039,-0.904647,-0.479766,4
4,0.873680,1.055601,0.639157,0.503558,0.685234,0.774689,0.730296,-1.169290,1.019946,-0.961753,5
...,...,...,...,...,...,...,...,...,...,...,...
88,0.616624,-0.691212,-4.355936,0.030519,-1.863836,-0.881542,-1.000087,-1.048665,-1.179589,-1.168319,101
89,0.616624,1.055601,-0.359862,0.030519,-0.009967,-0.053427,-1.000087,0.036966,-1.179589,-0.961753,102
90,-0.669273,-1.739299,-4.355936,0.030519,-1.863836,-0.053427,-0.134895,-1.410541,-1.179589,-1.168319,103
91,1.388100,-1.739299,0.139648,0.503558,0.685234,-0.053427,0.730296,1.122596,1.203240,1.413755,104
92,-1.697806,0.706238,-4.355936,-3.280754,-1.863836,-0.881542,0.730296,-0.928039,-1.179589,0.346498,106

### Detect student behavior changes

In [12]:
# When students' final scores are higher than their intertermediate scores, 'RES#' is 0
# When students' final scores are less than their intertermediate scores, 'RES#' is 1
std_whole_grades_with_stu_behavior = gp.get_result(std_whole_grades)
std_whole_grades_with_stu_behavior

,MID2,MID3,MID4,MID5,MID6,FIN2,FIN3,FIN4,FIN5,FIN6,ID,RES2,RES3,RES4,RES5,RES6
0,0.873680,-1.739299,0.139648,0.503558,0.221767,-0.881542,0.730296,1.243222,1.569829,1.448182,1,1,0,0,0,0
1,0.359568,0.706238,0.139648,0.503558,-0.936902,-0.053427,-0.134895,0.278217,0.011825,-0.824042,2,1,1,1,1,0
2,0.102203,0.706238,0.139648,0.503558,-1.863836,0.360631,0.730296,1.243222,0.470062,1.103906,3,0,1,0,1,0
3,1.388100,1.055601,0.639157,0.030519,0.685234,-0.881542,-1.432682,-0.928039,-0.904647,-0.479766,4,1,1,1,1,1
4,0.873680,1.055601,0.639157,0.503558,0.685234,0.774689,0.730296,-1.169290,1.019946,-0.961753,5,1,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,0.616624,-0.691212,-4.355936,0.030519,-1.863836,-0.881542,-1.000087,-1.048665,-1.179589,-1.168319,101,1,1,0,1,0
89,0.616624,1.055601,-0.359862,0.030519,-0.009967,-0.053427,-1.000087,0.036966,-1.179589,-0.961753,102,1,1,0,1,1
90,-0.669273,-1.739299,-4.355936,0.030519,-1.863836,-0.053427,-0.134895,-1.410541,-1.179589,-1.168319,103,0,0,0,1,0
91,1.388100,-1.739299,0.139648,0.503558,0.685234,-0.053427,0.730296,1.122596,1.203240,1.413755,104,1,0,0,0,0
92,-1.697806,0.706238,-4.355936,-3.280754,-1.863836,-0.881542,0.730296,-0.928039,-1.179589,0.346498,106,0,1,0,0,0

### Save the manipualted grade data

In [13]:
# If a user wants to use save them, 
# the user can save them as csv files by using the save_data function
# gp.save_grades(std_whole_grades_with_stu_behavior)

## 4. Merging log acitivities and grades into one data file

### Leave relevant columns only from intermediate and final grade data

In [14]:
outcome = std_whole_grades_with_stu_behavior[['ID', 'RES2', 'RES3', 'RES4', 'RES5', 'RES6','MID2','MID3','MID4','MID5','MID6']]
outcome

,ID,RES2,RES3,RES4,RES5,RES6,MID2,MID3,MID4,MID5,MID6
0,1,1,0,0,0,0,0.873680,-1.739299,0.139648,0.503558,0.221767
1,2,1,1,1,1,0,0.359568,0.706238,0.139648,0.503558,-0.936902
2,3,0,1,0,1,0,0.102203,0.706238,0.139648,0.503558,-1.863836
3,4,1,1,1,1,1,1.388100,1.055601,0.639157,0.030519,0.685234
4,5,1,1,1,0,1,0.873680,1.055601,0.639157,0.503558,0.685234
...,...,...,...,...,...,...,...,...,...,...,...
88,101,1,1,0,1,0,0.616624,-0.691212,-4.355936,0.030519,-1.863836
89,102,1,1,0,1,1,0.616624,1.055601,-0.359862,0.030519,-0.009967
90,103,0,0,0,1,0,-0.669273,-1.739299,-4.355936,0.030519,-1.863836
91,104,1,0,0,0,0,1.388100,-1.739299,0.139648,0.503558,0.685234
92,106,0,1,0,0,0,-1.697806,0.706238,-4.355936,-3.280754,-1.863836

### Merge log data with grade data

In [15]:
whole_data = lp.merge_all_data(std_manipulated_log_data, outcome)
whole_data[5] #Session 6

,ID,DUR_Aulaweb,DUR_Blank,DUR_Deeds,DUR_Diagram,DUR_FSM,DUR_Other,DUR_Properties,DUR_Study,DUR_TextEditor,...,MWC_Blank,MWC_Deeds,MWC_Diagram,MWC_FSM,MWC_Other,MWC_Properties,MWC_Study,MWC_TextEditor,MID6,Y
0,1,-0.206026,-0.187364,0.402963,-0.035197,-0.544723,-0.259192,0.164625,-0.653497,-0.164600,...,-0.109764,0.0,0.0,-0.199007,-0.156174,-0.109764,-0.170951,-0.19245,0.221767,0
1,2,0.098791,-0.210084,-0.358647,-0.350479,-0.520192,-0.206216,-0.607414,0.730816,-0.235257,...,-0.109764,0.0,0.0,-0.199007,-0.156174,-0.109764,-0.170951,-0.19245,-0.936902,0
2,4,-0.206706,0.134054,-0.398028,-0.171902,-0.359848,-0.259971,-0.388247,-0.735513,-0.222955,...,-0.109764,0.0,0.0,1.890571,-0.156174,-0.109764,-0.170951,-0.19245,0.685234,1
3,5,-0.207138,-0.210165,-0.374556,1.165346,-0.371774,-0.252044,-0.539273,-0.747055,-0.139567,...,-0.109764,0.0,0.0,-0.199007,-0.156174,-0.109764,-0.170951,-0.19245,0.685234,1
4,6,-0.206160,-0.129651,-0.291206,-0.346947,-0.606445,0.714986,0.214414,-0.134238,-0.200661,...,-0.109764,0.0,0.0,-0.199007,-0.156174,-0.109764,-0.170951,-0.19245,0.916968,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,96,-0.206680,-0.210741,-0.389445,-0.353762,-0.362886,-0.260186,2.095253,-0.364862,-0.236387,...,-0.109764,0.0,0.0,-0.199007,-0.156174,-0.109764,-0.170951,-0.19245,0.221767,0
75,98,-0.207138,-0.211083,-0.300417,2.312590,-0.114563,-0.182249,0.658939,-0.619342,0.092015,...,-0.109764,0.0,0.0,-0.199007,-0.156174,-0.109764,-0.170951,-0.19245,0.916968,1
76,99,-0.202553,0.000077,0.133643,-0.343044,0.112726,-0.023279,-0.432498,1.007607,-0.093921,...,-0.109764,0.0,0.0,-0.199007,-0.156174,-0.109764,-0.170951,-0.19245,-0.473434,1
77,102,-0.207138,-0.210651,-0.101544,-0.354645,0.012650,-0.258335,0.768677,-0.740111,-0.221300,...,-0.109764,0.0,0.0,-0.199007,-0.156174,-0.109764,-0.170951,-0.19245,-0.009967,1
78,104,-0.207090,-0.040951,-0.322334,0.727006,-0.769030,-0.244147,-0.404990,-0.265219,-0.223680,...,-0.109764,0.0,0.0,-0.199007,-0.156174,-0.109764,-0.170951,-0.19245,0.685234,0

### Save the combined data in a pickle file

In [16]:
# with open('whole_data.pkl', 'wb') as f:
#     pickle.dump(whole_data, f)

## 5. Detecting student behavior and clustering processess using machine learning

### Subset common important features across all sessions

In [17]:
# Subset common important features across all sessions 
# by using an ensemble learning method fundamentally based on decision trees
dt1 = whole_data.copy()
data_common_important_features = mm.subset_important_features(dt1, 3, "common")
data_common_important_features[1] #Session 2

    MCL_Properties  MCL_TextEditor   ID      MID2
0        -0.038297        0.518602    1  0.873680
1        -0.741354        2.304712    2  0.359568
2        -1.256930       -0.356903    3  0.102203
3        -0.835095        0.791589    4  1.388100
4         0.852243        0.150071    5  0.873680
..             ...             ...  ...       ...
70        2.445841        0.138372  100  0.102203
71       -0.038297       -0.275007  101  0.616624
72       -1.631894       -1.871977  102  0.616624
73        1.602171       -0.859978  103 -0.669273
74        0.289797       -0.668888  104  1.388100

[75 rows x 4 columns]

### Subset important features from each session

In [18]:
# Subset important features from each session
# by using an ensemble learning method fundamentally based on decision trees
dt2 = whole_data.copy()
data_different_important_features = mm.subset_important_features(dt2, 5, "different")
data_different_important_features[2] #Session 3

        MID3  MCL_Diagram  MM_Diagram  MCL_Properties  DUR_TextEditor  Y   ID
0   0.706238    -0.610939   -0.505354        0.052543       -0.661577  1    2
1   0.706238     1.295953    0.145194       -0.395617       -0.380935  1    3
2   1.055601     1.713821    0.444262       -1.023042        0.306333  1    4
3   1.055601     0.419018    0.954075       -0.305985       -0.439059  1    5
4   0.706238     0.625010    0.585514       -0.395617        0.206828  1    6
..       ...          ...         ...             ...             ... ..  ...
72  0.007513    -0.393176   -0.199880       -0.216353       -0.067015  1   99
73 -0.341849    -0.758075   -0.548642       -0.574881       -0.605739  0  100
74 -0.691212    -1.005265   -0.651265       -0.754146        0.475354  1  101
75  1.055601     1.331266    0.332451       -0.843778       -0.217277  1  102
76  0.706238     1.872729    5.909212        0.052543        0.042367  1  106

[77 rows x 7 columns]

### Detect student behavior changes

In [19]:
# Detect student behavior by fittng important log data and intermediate score into logistic regression
student_behavior_predictions = mm.machine_learning_model(data_different_important_features, 'LR')
student_behavior_predictions[2] # When Predicted_Y = 1, a student will get a notification from this system

,MID3,MCL_Diagram,MM_Diagram,MCL_Properties,DUR_TextEditor,Y,ID,Predicted_Y
0,0.706238,-0.610939,-0.505354,0.052543,-0.661577,1,2,1
1,0.706238,1.295953,0.145194,-0.395617,-0.380935,1,3,1
2,1.055601,1.713821,0.444262,-1.023042,0.306333,1,4,1
3,1.055601,0.419018,0.954075,-0.305985,-0.439059,1,5,1
4,0.706238,0.625010,0.585514,-0.395617,0.206828,1,6,1
...,...,...,...,...,...,...,...,...
72,0.007513,-0.393176,-0.199880,-0.216353,-0.067015,1,99,1
73,-0.341849,-0.758075,-0.548642,-0.574881,-0.605739,0,100,0
74,-0.691212,-1.005265,-0.651265,-0.754146,0.475354,1,101,0
75,1.055601,1.331266,0.332451,-0.843778,-0.217277,1,102,1
76,0.706238,1.872729,5.909212,0.052543,0.042367,1,106,1

### Student behavior prediction accuracy

In [20]:
print(accuracy_score(student_behavior_predictions[1]['Y'], student_behavior_predictions[1]['Predicted_Y']))
print(accuracy_score(student_behavior_predictions[2]['Y'], student_behavior_predictions[2]['Predicted_Y']))
print(accuracy_score(student_behavior_predictions[3]['Y'], student_behavior_predictions[3]['Predicted_Y']))
print(accuracy_score(student_behavior_predictions[4]['Y'], student_behavior_predictions[4]['Predicted_Y']))
print(accuracy_score(student_behavior_predictions[5]['Y'], student_behavior_predictions[5]['Predicted_Y']))

0.7866666666666666
0.8961038961038961
0.7931034482758621
0.7380952380952381
0.759493670886076

### Clustering students based on students' log activities and grades

In [21]:
dt3 = data_common_important_features.copy()
clustering_results = mm.kmean_clustering(dt3, 3, 3) # 3rd session and 3 clusters
clustering_results

    MCL_Properties_Mean  MCL_TextEditor_Mean   ID  MID_Mean  group
0             -0.038297             0.518602    1  0.873680      0
1             -0.344406             2.328672    2  0.532903      0
2             -0.826274            -0.365839    3  0.404221      2
3             -0.929069             0.345176    4  1.221850      0
4              0.273129            -0.348709    5  0.964640      1
..                  ...                  ...  ...       ...    ...
79             1.038496            -1.055962   68  0.706238      1
80            -0.843778            -1.044011   69 -1.389937      2
81            -0.216353             0.670244   75  1.055601      0
82             0.321439            -2.325387   89 -0.691212      2
83             0.052543             0.435215  106  0.706238      0

[84 rows x 5 columns]

### Frequencies of each cluster

In [22]:
frequencies = {}
for item in clustering_results['group']:
    if item in frequencies:
        frequencies[item] += 1
    else:
        frequencies[item] = 1
print(frequencies)

{0: 19, 2: 33, 1: 32}