In [1]:
import pandas as pd
import numpy as np

In [2]:
# load features and outcome
features_list = []
for i in range(2, 7):
    file_name = "scaled_variables_session_" + str(i) + ".csv"
    features = pd.read_csv('../EPM_dataset/Data/Seyoung/' + file_name)
    features_list.append(features)
    
outcome = pd.read_csv('../EPM_dataset/Data/Seyoung/grades.csv')

In [3]:
# verify
features_list[3]

,ID,DUR_Aulaweb,DUR_Blank,DUR_Deeds,DUR_Diagram,DUR_Other,DUR_Properties,DUR_Study,DUR_TextEditor,KS_Aulaweb,KS_Blank,KS_Deeds,KS_Diagram
0,1,0.105371,0.105120,0.105446,0.105440,0.102610,0.105324,0.105396,0.105407,-0.230749,-0.380389,-0.088532,-0.382027
1,2,0.105365,0.105124,0.105409,0.105362,0.102637,0.105234,0.105394,0.105407,-0.230749,0.652906,-0.697501,-0.472796
2,3,0.105365,0.105188,0.105409,0.105350,0.102687,0.105234,0.105414,0.105407,-0.230749,0.136259,-0.328126,-0.472796
3,4,0.105434,0.105293,0.105407,0.105369,0.102628,0.105241,0.105389,0.105407,1.553411,0.523744,-0.268227,1.977965
4,5,0.105365,0.105148,0.105406,0.105378,0.102610,0.105293,0.105390,0.105407,-0.230749,-0.380389,-0.018650,-0.382027
...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,100,0.105371,0.105123,0.105408,0.105388,0.102631,0.105240,0.105393,0.105408,0.180980,2.073686,0.111131,-0.018952
87,101,0.105365,0.105121,0.105405,0.105357,0.102617,0.105234,0.105388,0.105406,-0.230749,-0.380389,-0.777366,-0.109721
88,102,0.105365,0.105121,0.105413,0.105381,0.102694,0.105234,0.105385,0.105408,0.043737,-0.380389,-0.248261,-0.472796
89,103,0.105369,0.105576,0.105407,0.105378,0.102871,0.105237,0.105499,0.105407,-0.230749,0.136259,-0.158413,-0.472796
90,104,0.105369,0.105149,0.105406,0.105377,0.102694,0.105234,0.105387,0.105406,-0.230749,-0.380389,2.397262,0.298739

In [4]:
outcome

,Unnamed: 0,ID,MID2,MID3,MID4,MID5,MID6,FIN2,FIN3,FIN4,FIN5,FIN6,RES2,RES3,RES4,RES5,RES6
0,0,1,83.33,0.0,90.0,100.0,56.25,11.0,37.0,55.0,32.0,57.5,1,0,0,1,0
1,1,2,66.67,87.5,90.0,100.0,25.00,12.0,35.0,23.0,15.0,5.0,1,0,0,1,0
2,2,3,58.33,87.5,90.0,100.0,0.00,41.0,37.0,55.0,26.0,55.5,0,0,0,1,0
3,3,4,100.00,100.0,100.0,87.5,68.75,11.0,5.0,19.0,1.5,17.5,1,1,1,1,0
4,4,5,83.33,100.0,100.0,100.0,68.75,32.0,37.0,11.0,20.5,4.5,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,88,101,75.00,37.5,0.0,87.5,0.00,20.5,33.0,15.0,0.0,0.0,0,0,0,1,0
89,89,102,75.00,100.0,80.0,87.5,50.00,31.0,33.0,24.0,0.0,4.5,0,0,0,1,1
90,90,103,33.33,0.0,0.0,87.5,0.00,31.0,35.0,3.0,0.0,0.0,0,0,0,1,0
91,91,104,100.00,0.0,90.0,100.0,68.75,31.0,37.0,51.0,30.0,57.0,0,0,0,1,0
92,92,106,0.00,87.5,0.0,0.0,0.00,1.5,37.0,19.0,0.0,44.5,0,0,0,0,0

In [5]:
# leave relevant columns only
outcome = outcome[['ID', 'RES2', 'RES3', 'RES4', 'RES5', 'RES6']]
outcome

     ID  RES2  RES3  RES4  RES5  RES6
0     1     1     0     0     1     0
1     2     1     0     0     1     0
2     3     0     0     0     1     0
3     4     1     1     1     1     0
4     5     0     0     1     1     1
..  ...   ...   ...   ...   ...   ...
88  101     0     0     0     1     0
89  102     0     0     0     1     1
90  103     0     0     0     1     0
91  104     0     0     0     1     0
92  106     0     0     0     0     0

[93 rows x 6 columns]

In [6]:
# merge features and outcome
for i, features in enumerate(features_list):
    features_list[i] = features.merge(outcome[['ID', 'RES' + str(i+2)]], how='inner', on='ID')
    features_list[i] = features_list[i].rename(columns={'RES' + str(i+2): 'Y'})

In [7]:
# verify
features_list[2]

,ID,DUR_Aulaweb,DUR_Blank,DUR_Deeds,DUR_Diagram,DUR_Other,DUR_Properties,DUR_Study,DUR_TextEditor,KS_Aulaweb,KS_Blank,KS_Deeds,KS_Diagram,Y
0,1,-0.119438,-0.168084,-0.421963,-0.204503,-0.418698,-0.214326,-0.279388,0.273486,-0.319561,-0.375455,0.377517,-0.264516,0
1,2,-0.119368,-0.175045,0.710596,-0.240040,-0.336683,-0.191827,-0.330537,-0.507767,-0.319561,-0.375455,-0.640853,-0.437463,0
2,3,-0.119441,-0.173641,-0.533725,-0.150106,-0.511290,-0.219774,-0.229513,-0.390687,-0.319561,0.060131,0.004115,0.340799,0
3,4,-0.117265,-0.171369,-0.558895,-0.259557,-0.440508,0.091820,-0.478513,-0.616874,1.763701,0.495717,-0.029831,1.292008,1
4,5,-0.119447,-0.175162,0.766583,-0.521902,-0.234997,-0.225968,-0.502259,0.016013,-0.319561,-0.375455,-0.165614,-0.408639,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,94,-0.119301,-0.175148,0.434628,0.040961,0.504274,-0.215540,-0.180824,-0.217382,-0.319561,0.060131,0.445408,-0.350989,0
83,95,-0.119417,-0.175153,-0.053904,-0.441337,-0.531580,-0.198001,-0.455414,-0.548401,-0.319561,-0.375455,0.309626,-0.437463,0
84,96,-0.119115,-0.174914,-0.455312,-0.281876,-0.523948,-0.188123,-0.357168,-0.379249,-0.319561,-0.375455,-0.063777,-0.033920,0
85,98,-0.119447,-0.175164,1.265827,0.037912,-0.526390,-0.173015,-0.444261,0.039393,-0.319561,-0.375455,-0.029831,-0.437463,0
86,99,-0.119341,-0.175092,-0.474816,-0.004609,-0.246156,-0.198350,-0.447922,-0.469443,-0.319561,-0.230259,-0.199559,-0.437463,1

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix

In [18]:
for i, session in enumerate(features_list):
#     if i == 3: continue
    X = session.drop(columns=['ID', 'Y'])
    y = session['Y']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
    logmodel = LogisticRegression()
    logmodel.fit(X_train, y_train)
    predictions = logmodel.predict(X_test)
    print(f'==========Session{str(i+2)}===============')
    print('accuracy_score : ', accuracy_score(y_test, predictions))
    print('confusion_matrix : ', confusion_matrix(y_test, predictions))
    print('\n')

==========Session2===============
accuracy_score :  0.7391304347826086
confusion_matrix :  [[16  0]
 [ 6  1]]


==========Session3===============
accuracy_score :  0.7916666666666666
confusion_matrix :  [[19  1]
 [ 4  0]]


==========Session4===============
accuracy_score :  0.6666666666666666
confusion_matrix :  [[17  3]
 [ 6  1]]


==========Session5===============
accuracy_score :  0.9230769230769231
confusion_matrix :  [[ 0  0]
 [ 2 24]]


==========Session6===============
accuracy_score :  0.7916666666666666
confusion_matrix :  [[17  1]
 [ 4  2]]