In [29]:
# load libraries
import os
import glob
import pandas as pd
import numpy as np

The list "sessions" contains six elements, each of which represents students' behaviors and activities in a particular session

In [46]:
sessions = []
for root, dirs, files in os.walk("../EPM_dataset/Data/Processes/", topdown=False):
    if files:
        session = []
        for file in files:
            path = os.path.join(root, file)
            log = pd.read_csv(path, sep=",", header=None)
            session.append(log)

        session_pd = pd.concat(session)
        session_pd.columns = ["session", "student_id", "exercise", 
                      "activity",'start_time','end_time',
                     'idle_time','mouse_wheel','mouse_wheel_click','mouse_click_left',
                     'mouse_click_right','mouse_movement','keystroke']
        sessions.append(session_pd)

sessions[0].head()

,session,student_id,exercise,activity,start_time,end_time,idle_time,mouse_wheel,mouse_wheel_click,mouse_click_left,mouse_click_right,mouse_movement,keystroke
0,4,61,Es,Other,13.11.2014 11:41:59,13.11.2014 11:42:0,0,0,0,0,0,0,0
1,4,61,Es,Other,13.11.2014 11:42:0,13.11.2014 11:42:0,0,0,0,2,0,23,0
2,4,61,Es,Aulaweb,13.11.2014 11:42:1,13.11.2014 11:42:3,0,0,0,2,0,223,0
3,4,61,Es,Other,13.11.2014 11:42:4,13.11.2014 11:42:7,281,0,0,6,0,171,0
4,4,61,Es,Aulaweb,13.11.2014 11:42:8,13.11.2014 11:42:14,3364,0,0,6,0,24,14

In [47]:
# sessions[] contains all data for Session1
for i, session in enumerate(sessions):
    session_num = session['session'].unique()[0]
    print(f"{i}th element in the sessions list represents Session{session_num}")

0th element in the sessions list represents Session4
1th element in the sessions list represents Session3
2th element in the sessions list represents Session2
3th element in the sessions list represents Session5
4th element in the sessions list represents Session6
5th element in the sessions list represents Session1

In [48]:
# reorgaize sessions list
data_list = [0]*7
session_num = 0
while sessions:
    session_num = int(sessions[0]['session'].unique())
    data_list[session_num] = sessions.pop(0)
    session_num +=1

# confirm
for i, session in enumerate(data_list):
    if i == 0:
        continue
    session_num = session['session'].unique()[0]
    print(f"{i}th element in the sessions list represents Session{session_num}")

1th element in the sessions list represents Session1
2th element in the sessions list represents Session2
3th element in the sessions list represents Session3
4th element in the sessions list represents Session4
5th element in the sessions list represents Session5
6th element in the sessions list represents Session6